# ======================================================================= # 
#                           Fibonacci Sequence                            #
# ======================================================================= #
#                                                                         #
# Instructions:                                                           #
# ----------------------------------------------------------------------- #
# Each new term in the Fibonacci sequence is generated by adding the      #
# previous two terms. By starting with 1 and 2, the first 10 terms will   #
# be:                                                                     #
#                                                                         #
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                                  #       
#                                                                         #
# By considering the terms in the Fibonacci sequence whose values do not  #
# exceed four million, find the sum of the even-valued terms.             #
#                                                                         #
# Answer: 4613732                                                         #
# ----------------------------------------------------------------------- #

fibonacci_list = []
num1 = 0
num2 = 1
new_num = 0
sum_of_even = 0
limit = 4000000

while True:
    new_num = num1 + num2
    if new_num < limit:
        fibonacci_list.append(new_num)
        num1 = num2
        num2 = new_num
    else:
        break

for number in fibonacci_list:
    if number % 2 == 0:
        sum_of_even += number

print sum_of_even